import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import Link from "next/link";
import App from "../components/Map";


export default function Home({ exploreData, cardsData, externalPostData }) {
  return (
    <div>
      <Head>
        <title>papa airbn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*header*/}
      <Header />
      {/* banner */}
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {/* pull on server side api endpoint */}
          <div className="grid grid-col-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                key={img}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">fasilitas</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3">
            {cardsData?.map(({ id, mainUrl }) => (
              <MediumCard key={id} img={mainUrl}  />
            ))}
          </div>
        </section>
        <LargeCard
          img="https://Links.papareact.com/4cj"
          title="the greatest Outdoors"
          desciption="wishlists curated by airbnb"
          buttonText="Get Inspired"
        />
        {externalPostData.map((data) => {
          return (
            <div key={data.id}>
              <Link href={data.link}>
                <h3>{data.title}</h3>
              </Link>
              <p>{data.body}</p>
            </div>
          );
        })}
         <section className="hidden xl:inline-flex xl:min-w-[600px]">
            <App/>
        </section>
      </main>
      <Footer />
    </div>
  );
}
export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(
    (res) => res.json()
  );
  const cardsData = await fetch(
    "https://hotels-com-provider.p.rapidapi.com/v1/hotels/photos?hotel_id=363464",
    {
      method: "GET",
      headers: {
        "x-rapidapi-host": "hotels-com-provider.p.rapidapi.com",
        "x-rapidapi-key": "1986c8e022msh1534cf98bff4ec1p19e90djsn31884e72df1c",
      },
    }
  ).then((res) => res.json());
  const apiURL = "http://localhost:3004/posts";

  const response = await fetch(apiURL);

  const data = await response.json();

  return {
    props: {
      exploreData,
      cardsData,
      externalPostData: data,
    },
  };
}
